#!/bin/bash

set -euf -o pipefail

DIR="$(cd $(dirname "$0")/.. && pwd)"

ID="$DIR/.my-secret-identity"

TEAM_FILE="$DIR/team.identities"

TMP_FILE=$(mktemp)

function cleanup()
{
    rm $TMP_FILE
    # try to remove backup files
    rm $TMP_FILE* 2>1 || true
}


age --decrypt --identity "$ID" "$1" > $TMP_FILE

# make sure the decrypted file is deleted
trap cleanup EXIT

$EDITOR $TMP_FILE

cat $TMP_FILE | age --encrypt --recipients-file "$TEAM_FILE" --output "$1"

