#!/bin/bash

set -euf -o pipefail

DIR="$(cd $(dirname "$0")/.. && pwd)"

TMP_FILE=$(mktemp)

function cleanup()
{
    # try to remove possible backup files too
    rm -f $TMP_FILE*
}

"$DIR"/cmd/read-team-secret "$1" >$TMP_FILE

# make sure the decrypted file is deleted
trap cleanup EXIT

$EDITOR $TMP_FILE

"$DIR"/cmd/upsert-team-secret "$1" <$TMP_FILE
