#!/bin/bash

set -euf -o pipefail

DIR="$(cd $(dirname "$0")/.. && pwd)"

ID="$DIR/.my-secret-identity"

CLEARTEXT=$(age --decrypt --identity "$ID" "$1")

# $CLEARTEXT may contain trailing newlines, which are inconvenient to keep when
# the output is a pipe (e.g. to pbcopy/xsel). We remove them.
if [[ -t 1 ]]; then  # "is stdout a terminal?"
    printf "%s\n" "$CLEARTEXT"
else  # stdout is a pipe
    printf "%s" "$CLEARTEXT"
fi
