#!/bin/bash

set -eu -o pipefail
shopt -s failglob

SECRETS_DIR="$1"

DIR="$(cd $(dirname "$0")/.. && pwd)"

ID="$DIR/.my-secret-identity"
TEAM_FILE="$DIR/team.identities"

for file in "$SECRETS_DIR"/*; do
    age --decrypt --identity $ID "$file" | "$DIR"/cmd/upsert-team-secret "$file"
done

echo "Done!"
