#!/bin/bash

set -eu -o pipefail
shopt -s failglob

DIR="$(cd $(dirname "$0")/.. && pwd)"

ID="$DIR/.my-secret-identity"
TEAM_FILE="$DIR/team.identities"

for file in "$DIR"/secrets/*; do
    age --decrypt --identity $ID "$file" | "$DIR"/cmd/upsert-team-secret "$file"
done

echo "Done!"
