#!/bin/bash

set -euf -o pipefail

SECRETS_DIR="$1"

DIR="$(cd $(dirname "$0")/.. && pwd)"

find "$SECRETS_DIR" -type f -print | while read -r file; do
    "$DIR"/cmd/read-team-secret "$file" | "$DIR"/cmd/upsert-team-secret "$file"
done

echo "Done!"
