#!/bin/bash

set -euf -o pipefail

DIR="$(cd $(dirname "$0")/.. && pwd)"

TEAM_FILE="$DIR/team.identities"

mkdir -p $(dirname "$1")
# printf removes trailing newlines.
printf "%s" "$(cat)" | age --encrypt --recipients-file "$TEAM_FILE" --output "$1"
